version: "3.9"

services:
  ollama:
    container_name: llm-server
    build: ./llm-server
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      ama-wine:
          ipv4_address: 172.24.0.10

  fastapi:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    networks:
      ama-wine:
        ipv4_address: 172.24.0.12

volumes:
  ollama:
networks:
  ama-wine:
    name: ama-wine
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.24.0.0/16
